# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Manipulando arquivos TXT
#-------------------------

texto = "Meu objetivo é ser um dos melhores Cientistas de Dados do mundo!"
print(texto)

#Importando o pacote OS - Operating System - serve para manipular o sistema operacional
import os

#Criando um arquivo
arquivo = open(os.path.join('arquivos/cientista.txt'),'w')

#Gravando os dados no arquivo
for palavra in texto.split():
  arquivo.write(palavra + ' ')

#Fechando arquivo
arquivo.close()

#Lendo o arquivo
arquivo = open('arquivos/cientista.txt','r')
conteudo = arquivo.read()
arquivo.close()

print(conteudo)

#Usando a expressao WITH
with open('arquivos/cientista.txt','r') as arquivo:
  conteudo = arquivo.read()

print(len(conteudo))

print(conteudo)

with open ('arquivos/cientista.txt','w') as arquivo:
  arquivo.write(texto[:21])#Slicing
  arquivo.write('\n')
  arquivo.write.close(texto[:33])#Slicing

  #Lendo o arquivo
  arquivo = open('arquivos/cientista.txt','r')
  conteudo = arquivo.read()
  arquivo.close()

  print (texto)