# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Manipulando arquivos JSON (Java Script Object Notation)

#Criando um dicionário
dict = {"Nome": "Rafael",
        "linguagem": "Python",
        "Idade" : 30,
        "Major" : "Data Scientist"
}
for k,v in dict.items():
  print(k,v)

#Importando o módulo JSON
import json

#Convertendo o dicionário para um objeto JSON
json.dumps(dict)

#Criando um arquivo Json
with open("arquivos/dados.json",'w') as arquivo:
  arquivo.write(json.dumps(dict))

#Leitura de arquivo Json
with open('arquivo/dados.json','r') as arquivo:
  texto = arquivo.read()
  data = json.loads(texto)

print(data)
print(data['nome'])

#Imprimindo um arquivo Json copiado da internet
from urllib.request import urlopen

response = urlopen("http://vimeo.com/api/v2/video/57733101.json").read().decode('utf8')
data = json.loads(response)[0]

print ('Título: ',data['title'])
print('URL: ',data['url'])
print('Duração: ',data['duration'])
print('Número de Visualizações: ',data['stats_number_of_plays'])

#Copiando o conteúdo de um arquivo para outro
import os

arquivo_fonte = "arquivos/dados.json"
arquivo_destino = "arquivos/json_data.txt"

#Método 1
with open ('arquivo_fonte','r') as infile:
  text = infile.read()
  with open(arquivo_destino,'w') as outfile:
    outfile.write(text)

#Método 2
open(arquivo_destino,'w').write(open(arquivo_fonte,'r').read())

#Leitura de ariquivo Json
with open('arquivos/json_data.txt','r') as arquivo:
  texto = arquivo.read()
  data = json.loads(texto)

print(data)