# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Funções Built-in para Data Science

#Função Map
#Ela é uma função de recebe 2 argumentos: uma função e uma sequência 'lista'
# map(função,sequencia)

#Criando duas funções
#Função 1 - Recebe uma temperatura como paramentro e retorna a temperatura em Fahrenheit
def fahrenheit(T):
  return ((float(9)/5)*T + 32)

#Função 2 - Recebe uma temperatura como paramentro e retorna a temperatura em Celsius
def celsius(T):
  return ((float(5)/9)*T - 32)

#Criando uma lista
temperaturas = [0, 22.5, 40, 100]

#Aplicando a função a cada elemento da lista de temperaturas.
#Em Python 3, a função map() retorna um iterator ( precisa converter para uma lista)
map(fahrenheit,temperaturas)

#Função map() retornando a lista de temperaturas convertidas em Fahrenheit
list(map(fahrenheit,temperaturas))

#Usando um loop for para imprimir o resultado da função map()
for temp in map(fahrenheit,temperaturas):
  print(temp)

#Convertendo para Celsius
map(celsius, temperaturas)

#Função map() retornando a lista de temperaturas convertidas em Celsius
list(map(celsius,temperaturas))

#Usando Lambda
map(lambda x: (5.0/9)*(x - 32), temperaturas)
list(map(lambda x: (5.0/9)*(x - 32),temperaturas))

#Somando os elementos de 2 listas
a = [1,2,3,4]
b = [5,6,7,8]
list(map(lambda x,y : x+y,a,b))

#Somando os elementos de 3 listas
a = [1,2,3,4]
b = [5,6,7,8]
c = [9,10,11,12]
list(map(lambda x,y,z : x+y+z,a,b,c))