# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Funções Built-in para Data Science

#Função Filter
#Ela é uma função de recebe 2 argumentos: uma função e uma sequência 'lista'
# reduce(função,sequencia) 
#Ela filtra os elementos de uma sequencia para os quais a função retorne True(bool)

#Criando uma funcao
def verificarPar (num):
  if num % 2 == 0:
    return True
    else:
      return False

#Chamando a função e passando um número como parâmetro.
#Retornará Falso se for impar e True se for Par.
verificarPar(35)

lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10, 11, 12, 13, 14, 15, 16, 17, 18]
filter(verificadorPar, lista)#è necessario converte numa lista
list(filter(verificadorPar, lista))
list(filter(lambda x: x%2==0, lista))
list(filter(lambda num: num > 8, lista))