# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Funções Built-in para Data Science

# Função Enumerate() retorna o indice de cada valor em uma sequencia,
# a medida que percorre toda a sequencia, retornando uma tupla no formato
# (índice,valor)
# enumerate (sequencia)

#Criando uma lista
seq ['a','b','c']
enumerate(seq)
list(enumerate(seq))

#Imprimindo os valores de uma lista com a funcao enumerate() e 
#seus respectivos índices.

for indice,valor in enumerate(seq):
  print(indice,valor)

for indice, valor in enumerate(seq)
  if indice >= 2:
    break
  else:
    print(valor)

lista = ['Marketing','Tecnologia', 'Business']
for i, item in enumerate (lista)
print(i,item)

for i, item in enumerate ('Isso é uma string'):
  print(i, item)

for i, item in enumerate(range(10)):
  print(i,item)