# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Funções Built-in para Data Science

# Função Zip() agrega os valores de duas sequencias e retorna uma tupla
# zip(sequencia,sequencia)

#Criando duas listas
x = [1, 2, 3]
y = [4, 5, 6]

#Unindo as listas. Em Python 3 retorna um iterator
zip(x,y)
list(zip(x,y))

# Atenção quando as sequencias tiverem numero diferente de elementos
list(zip('ABCD', 'xy'))

#Criando duas listas
a = [1, 2, 3]
b = [4, 5, 6, 7, 8]

list(zip(a,b))

#Criando e dicionarios
d1 = {'a':1, 'b':2}
d2 = {'c':4, 'd':5}

# Zip vai unir as chaves
list(zip(d1,d2))

# Zip vai unir os valores(itens)
list(zip(d1,d2.values()))

#Criando uma função para trocar valores entre 2 dicionarios
def trocaValores(d1,d2):
  dicTemp = {}

  for d1key, d2val in zip(d1,d2.values()):
    divTemp[d1key] = d2val

  return dicTemp

trocaValores(d1,d2)

