# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Funções Built-in para Data Science

#List Comprehension: Aplica uma expressao arbitraria(ao inves de aplicar
#apenas uma funcao) a uma sequencia de elementos.
# Exemplo: lst = [x for x in 'sequencia']

#Retornar o caracter em uma sequencia de caracteres
lst = [x for x in 'Python']

#Check
lst
type(lst)

#Raiz quadrada e um range de numeros e retornar uma lista
lst = [x**2 for x in range (0, 11)]
lst

#Verificar os numeros pares em um range de numeros
lst = [x for x in range(11) if x % 2== 0]
lst

#Converter Celsius para Fahrenheit
celsius = [0, 10, 20, 34.5]

fahrenheit = [ ((float(9)/5)*temp + 32)for temp in celsius]
fahrenheit

#Operações aninhadas
lst = [x**2 for x in [x**2 for x in range(11)]]
lst