# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Módulos
#Módulo Math

#Importando o módulo Math
import math

#Verificando todos os métodos disponiveis no modulo
dir(math)

#Utilizando um dos métodos do módulo Math
math.sqrt(25)#Raiz quadrada

#Importando apenas um dos métodos do módulo math
from math import sqrt
sqrt(9)#Usando o método

#Imprimindo todos os métodos do módulo Math
print(dir(math))

#Help do método sqrt do módulo math
help(sqrt)

#Importando o módulo ramdom
import random #Aleatório
random.choice(['Maça','Banana','Laranja'])#Escolha aleatória
ramdom.sample(range(100),10)#Amostra aleatória

#Importando o módulo statistics
import statistics
dados = [2.75,1.75,1.25,0.25,0.5,1.25,3.5]
statistics.mean(dados)#Calculando a média
statistics.median(dados)#Calculando a mediana

#Importando o módulo OS - Operating System
import os
os.getcwd()#Saber qual o diretório atual
print(dir(os))

#Importando o módulo Sys
import sys#Interagir com o SO
sys.stdout.write('Teste')
sys.version

#Importando o módulo request do pacote urllib, usado para trazer url's
#para dentro do nosso ambiente Python
import urllib.request

#Váriável resposta armazena o objeto de conexão a url passada como parâmetro
resposta = urllib.request.urlopen('http://python.org')

#Objeto resposta
print(resposta)

# Chamando o método read() do objeto resposta e armazenado o código
#html na variável html
html = resposta.read()

#Imprimindo html
print(html)