# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Módulo Datetime

 #Importando o módulo Datetime
 import datetime
 agora = datetime.datetime.now()#pacote datetime , modulo datetime , momento now
 agora
 t = datetime.time(7,43,28)
 print(t)
 print ('Hora : ', t.hour)
 print ('Minuto : ',t.minute)
 print ('Segundos : ',t.second)
 print ('Microsegundo : ', t.microsecond)
 print (datetime.time.min)
 hoje = datetime.date.today()
 print (hoje)
 print ('ctime: ', hoje.ctime())

 #Calculos em datas
 d1 = datetime.date(2018, 4, 28)
 print('d1:',d1)

 d2 = d1.replace(year=2016)
 print('d2:',d2)

 #Diferença em dias entre duas datas
 d2 - d1# O resultado será a diferença em dias